# Settings
baseurl: 
permalink: /:categories/:title

# About
title: ISI2
tagline: Ingénierie des Systèmes d'Information
authors:
  - name: Baptiste Pesquet
    url: 'http://bpesquet.fr'
created: 
license:
  name: Creative Commons BY-NC-SA 4.0
  shortname: CC BY-NC-SA 4.0
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/
  badge: http://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png

# Default values
defaults:
  - scope:
      path: ''
    values:
      addons:
        highlightjs: yes
        print-link: yes
        about: yes


